<?
  function mschedule($month){
    //Copyright 2018. ms214 All Rights Reserved.
    //http://blog.ms214.kr/
    $schedule = array();
    for($i = 0; $i<31; $i++){
      $schedule[$i] = $month."월".($i+1)."일 : ";
    }
    if($month == "3월"){
      $schedule[0] .="\\n";
      $schedule[1] .="입학식(1) 개학식(2,3)\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="\\n";
      $schedule[5] .="\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="\\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] .="\\n";
      return $schedule;
    }//3월 if문 끝
    else if($month == "4월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="\\n";
      $schedule[5] .="\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="\\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="중간고사(2,3) \\n";
      $schedule[30] ="";
      return $schedule;
    }
    else if($month == "5월"){
      $schedule[0] .= "중간고사(2,3) \\n";
      $schedule[1] .= "중간고사(2,3) \\n";
      $schedule[2] .= "\\n";
      $schedule[3] .= "\\n";
      $schedule[4] .= "어린이날\\n";
      $schedule[5] .= "\\n";
      $schedule[6] .= "대체휴일 \\n";
      $schedule[7] .= "\\n";
      $schedule[8] .= "\\n";
      $schedule[9] .= "개교기념일 \\n";
      $schedule[10] .= "\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="\\n";
      $schedule[14] .="체험학습\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="재량휴업일\\n";
      $schedule[21] .="석가탄신일\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] .="\\n";
      return $schedule;
    }//5월if문 끝
    else if($month =="6월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="\\n";
      $schedule[5] .="현충일\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="영어듣기\\n";
      $schedule[12] .="지방선거일 \\n";
      $schedule[13] .="\\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18].="학업성취도평가 \\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] ="";
      return $schedule;
    }//6월 if문 끝
    else if($month == "7월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .= "기말고사 \\n";
      $schedule[5] .= "기말고사 \\n";
      $schedule[6] .= "\\n";
      $schedule[7] .= "\\n";
      $schedule[8] .= "기말고사 \\n";
      $schedule[9] .= "기말고사 \\n";
      $schedule[10] .= "\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="\\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .= "방학식 \\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] .="\\n";
      return $schedule;
    }//7월 if문 끝
    else if($month == "8월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="\\n";
      $schedule[5] .="\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="개학일 \\n";
      $schedule[13] .="\\n";
      $schedule[14] .="광복절 \\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="수련활동\\n";
      $schedule[29] .="수련활동\\n";
      $schedule[30] .="수련활동\\n";
      return $schedule;
    }//8월 if문 끝
    else if($month == "9월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="\\n";
      $schedule[5] .="\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="\\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="추석 연휴\\n";
      $schedule[24] .="추석 연휴\\n";
      $schedule[25] .="추석 연휴\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] = "";
      return $schedule;
    }//9월 if문 끝
    else if($month == "10월"){
      $schedule[0] .="\\n";
      $schedule[1] .="중간고사(2,3)\\n";
      $schedule[2] .="개천절 \\n";
      $schedule[3] .="중간고사(2,3)\\n";
      $schedule[4] .="중간고사(2,3)\\n";
      $schedule[5] .="\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="한글날\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="\\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="영어듣기\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] .="\\n";
      return $schedule;
    }//10월 if문 끝
    else if($month == "11월"){
      $schedule[0] .="기말고사(3)\\n";
      $schedule[1] .="기말고사(3)\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="기말고사(3)\\n";
      $schedule[5] .="기말고사(3)\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .= "\\n";
      $schedule[14] .="대학수학능력시험 \\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] = "";
      return $schedule;
    }//11월 if문 끝
    else if($month == "12월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="\\n";
      $schedule[5] .="\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="기말고사(2) \\n";
      $schedule[11] .="기말고사(2) \\n";
      $schedule[12] .="기말고사(2) \\n";
      $schedule[13] .="기말고사(2) \\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="성탄절\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="방학식\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] = "\\n";
      return $schedule;
    }//12월 if문 끝
    else if($month == "1월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="\\n";
      $schedule[4] .="\\n";
      $schedule[5] .="\\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="\\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="\\n";
      $schedule[14] .="\\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] .="\\n";
      $schedule[29] .="\\n";
      $schedule[30] = "\\n";
      return $schedule;
    }//1월 if문 끝
    else if($month == "2월"){
      $schedule[0] .="\\n";
      $schedule[1] .="\\n";
      $schedule[2] .="\\n";
      $schedule[3] .="설 연휴 \\n";
      $schedule[4] .="설 연휴 \\n";
      $schedule[5] .="설 연휴 \\n";
      $schedule[6] .="\\n";
      $schedule[7] .="\\n";
      $schedule[8] .="\\n";
      $schedule[9] .="\\n";
      $schedule[10] .="개학식 \\n";
      $schedule[11] .="\\n";
      $schedule[12] .="\\n";
      $schedule[13] .="졸업식 \\n";
      $schedule[14] .="종업식 \\n";
      $schedule[15] .="\\n";
      $schedule[16] .="\\n";
      $schedule[17] .="\\n";
      $schedule[18] .="\\n";
      $schedule[19] .="\\n";
      $schedule[20] .="\\n";
      $schedule[21] .="\\n";
      $schedule[22] .="\\n";
      $schedule[23] .="\\n";
      $schedule[24] .="\\n";
      $schedule[25] .="\\n";
      $schedule[26] .="\\n";
      $schedule[27] .="\\n";
      $schedule[28] ="";
      $schedule[29] ="";
      $schedule[30] ="";
      return $schedule;
    }else{
      return "잘못된 입력입니다.";
    }
  }
?>
